export const dummyData = [
  {
    user_id: 1,
    email: "john@gmail.com",
    site_id: 1,
    role: "Super Admin",
  },
  {
    user_id: 2,
    email: "mary@gmail.com",
    site_id: 2,
    role: "User",
  },
  {
    user_id: 3,
    email: "daniel@gmail.com",
    site_id: 1,
    role: "Owner",
  },
  {
    user_id: 4,
    email: "david@gmail.com",
    site_id: 3,
    role: "Admin",
  },
  {
    user_id: 5,
    email: "emily@gmail.com",
    site_id: 2,
    role: "User",
  },
  {
    user_id: 6,
    email: "james@gmail.com",
    site_id: 1,
    role: "Super Admin",
  },
  {
    user_id: 7,
    email: "sarah@gmail.com",
    site_id: 4,
    role: "User",
  },
  {
    user_id: 8,
    email: "michael@gmail.com",
    site_id: 5,
    role: "Admin",
  },
  {
    user_id: 9,
    email: "katherine@gmail.com",
    site_id: 1,
    role: "Owner",
  },
  {
    user_id: 10,
    email: "william@gmail.com",
    site_id: 6,
    role: "User",
  },
  {
    user_id: 11,
    email: "charles@gmail.com",
    site_id: 1,
    role: "Super Admin",
  },
  {
    user_id: 12,
    email: "helen@gmail.com",
    site_id: 7,
    role: "User",
  },
  {
    user_id: 13,
    email: "henry@gmail.com",
    site_id: 8,
    role: "Admin",
  },
  {
    user_id: 14,
    email: "patricia@gmail.com",
    site_id: 1,
    role: "Owner",
  },
  {
    user_id: 15,
    email: "robert@gmail.com",
    site_id: 9,
    role: "User",
  },
  {
    user_id: 16,
    email: "linda@gmail.com",
    site_id: 10,
    role: "User",
  },
  {
    user_id: 17,
    email: "richard@gmail.com",
    site_id: 11,
    role: "Admin",
  },
  {
    user_id: 18,
    email: "barbara@gmail.com",
    site_id: 1,
    role: "Super Admin",
  },
  {
    user_id: 19,
    email: "charles@gmail.com",
    site_id: 12,
    role: "User",
  },
  {
    user_id: 20,
    email: "susan@gmail.com",
    site_id: 13,
    role: "User",
  },
  {
    user_id: 21,
    email: "william@gmail.com",
    site_id: 14,
    role: "Admin",
  },
  {
    user_id: 22,
    email: "john@gmail.com",
    site_id: 1,
    role: "Owner",
  },
  {
    user_id: 23,
    email: "mary@gmail.com",
    site_id: 15,
    role: "User",
  },
  {
    user_id: 24,
    email: "daniel@gmail.com",
    site_id: 16,
    role: "User",
  },
  {
    user_id: 25,
    email: "david@gmail.com",
    site_id: 17,
    role: "Admin",
  },
  {
    user_id: 26,
    email: "emily@gmail.com",
    site_id: 1,
    role: "Super Admin",
  },
  {
    user_id: 27,
    email: "james@gmail.com",
    site_id: 18,
    role: "User",
  },
  {
    user_id: 28,
    email: "sarah@gmail.com",
    site_id: 19,
    role: "User",
  },
  {
    user_id: 29,
    email: "michael@gmail.com",
    site_id: 20,
    role: "Admin",
  },
  {
    user_id: 30,
    email: "katherine@gmail.com",
    site_id: 1,
    role: "Owner",
  },
];
